<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OrbitalAuthority.ECS</RootNamespace>
    <AssemblyName>OrbitalAuthority.ECS</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <!-- ECS зависит только от Core -->
  <ItemGroup>
    <ProjectReference Include="..\OrbitalAuthority.Core\OrbitalAuthority.Core.csproj" />
  </ItemGroup>

</Project>