<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrbitalAuthority.Core\OrbitalAuthority.Core.csproj" />
    <ProjectReference Include="..\OrbitalAuthority.Data\OrbitalAuthority.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OrbitalAuthority.Gameplay</RootNamespace>
    <AssemblyName>OrbitalAuthority.Gameplay</AssemblyName>
  </PropertyGroup>

</Project>
